src/dftd3/cutoff.f90, test/unit/test_periodic.f90
=> Add support for 1D and 2D periodic boundary conditions

.github/workflows/wheel.yml
=> Use conda-forge instead of PyPI to provision sdist workflow

.github/workflows/build.yml, python/dftd3/pyscf.py, python/dftd3/test_pyscf.py
See https://github.com/pyscf/pyscf/blob/8b3fef8cf18f10d430261d4a8bea21fadf19bb1f/pyscf/scf/hf.py#L1054-L1076.
Closes #37
=> PySCF: Add support for recording dispersion energy

app/driver.f90, src/dftd3.f90, src/dftd3/disp.f90, src/dftd3/output.f90
- print atomic dispersion energies in Hartree and kcal/mol
- requires additional verbosity level (i.e., >2)
<details>
<summary>Example Output</summary>
```
-----------------------------------
s i m p l e   D F T - D 3  v1.0.0
-----------------------------------
Rational (Becke-Johnson) damping: D3(BJ)
---------------------
s6         1.0000
s8         2.4000
s9         0.0000
a1         0.6300
a2         5.0000
alp        14.0000
--------------------
Atom-resolved dispersion energies:
--------------------------------------------------
--------------------------------------------------
1   11 Na  -0.76748306E-03     -0.48160289
2    1 H   -0.24893380E-03     -0.15620832
3    8 O   -0.36382575E-03     -0.22830411
4    1 H   -0.28480067E-03     -0.17871512
5    9 F   -0.30407223E-03 …
```
=> Print atomic dispersion energies

python/dftd3/pyscf.py
Update grad interface due to api changes in pyscf-2.4. See also issue https://github.com/pyscf/pyscf/issues/1986
=> Update interface for gradient for PySCF 2.4

.github/workflows/docs.yml
- add permission for `GITHUB_TOKEN` (as described [here](https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane))
- update versions of actions
Workflow fails due to missing write permissions in: Settings -> Actions -> General -> Workflow permissions.
=> Fix build workflow

.github/workflows/wheel.yml
Python 3.12 is now the default on Ubuntu 24.04, so this adds a binary distribution for python 3.12 to the CI.
=> Binary distribution for Python 3.12

python/dftd3/pyscf.py, python/dftd3/test_pyscf.py
Fix for https://github.com/dftd3/simple-dftd3/issues/73
Checks if the `mol.lattice_vectors()` method exists, rather than checking if the mol is an instance of `pyscf.pbc.gto.Cell` specifically
=> Fix periodic PySCF calculations

src/dftd3/output.f90, src/dftd3/reference.f90
Implements the workarounds for Cray compilers mentioned in #76.
Closes #76.
=> Workarounds for Cray compilers

.github/workflows/wheel.yml, python/dftd3/meson.build, python/dftd3/test_interface.py, python/mesonpep517.toml
This *should* fix https://github.com/dftd3/simple-dftd3/issues/62.
`setuptools` is now a required build dependency for Python 3.12, see https://cffi.readthedocs.io/en/stable/whatsnew.html#v1-16-0.
It wasn't super clear to me how the wheels that land on PyPI are generated. To test this I downloaded the current source distribution, modified the `pyproject.toml` file, and tested that the installation works.
Someone needs to make sure that this also works with your workflow/in the CI.
The same patch should be applicable to [dftd4](https://github.com/dftd4/dftd4/blob/main/python/pyproject.toml#L2) and [tblite](https://github.com/dftd4/dftd4/blob/main/python/pyproject.toml#L2).
Linked issues for reference: https://github.com/tblite/tblite/issues/195 https://github.com/tblite/tblite/issues/198 …
=> Fix python3.12 build failure

assets/ci/build-env.yaml, python/dftd3/interface.py
Uses raw strings to supress the `SyntaxWarning` thrown by python3.12.
=> Fixes invalid escape sequences

app/cli.f90
Fixes #84 
Now, it works as expected:
```
$ ./s-dftd3 CO.xyz --bj tpss --grad hdfgd
<...>
Virial:
--------------------------------------------------
component           x          y          z
--------------------------------------------------
x       0.000E+00  0.000E+00  0.000E+00
y       0.000E+00  0.000E+00  0.000E+00
z       0.000E+00  0.000E+00  1.711E-06
--------------------------------------------------
[Info] Dispersion energy written to .EDISP
[Info] Dispersion results written to 'hdfgd'
```
=> Do not override grad_output at the end of arguments parsing

doc/api/fortran.rst
=> Fix example in Fortran API

config/cmake/s-dftd3-utils.cmake, doc/installation.rst
=> Update docs on build

doc/tutorial/first-steps-fortran.rst, doc/tutorial/first-steps-fortran/app/main.f90, doc/tutorial/first-steps-fortran/fpm.toml, doc/tutorial/first-steps-fortran/src/scan.f90, doc/tutorial/index.rst
=> Add tutorial on usage of Fortran API

README.md, app/cli.f90, app/meson.build, docs.md, test/validation/02-energy-d3-zero.resp
- implement -- to stop parsing for arguments in CLI
- fix typo for pip installation of docs requirements
- mention default URL for HTTP server
=> Minor updates

python/dftd3/parameters.py
When the new D3 was picked up in QCEngine testing on Windows, it can't find the parameters file. Further below are traces from the conda-forge builds showing relative positioning on Linux and Windows. So I think this patch should fix up Windows, but it hasn't been tested.
```
dftd3-python              1.2.0           py312h2c12667_1    conda-forge
simple-dftd3              1.2.0                h28841b1_2    conda-forge
```
```
File "D:\a\QCEngine\QCEngine\qcengine\programs\empirical_dispersion_resources.py", line 1055, in <module>
dashcoeff["d3bjatm"]["definitions"].update(_get_d3_definitions("bj"))
^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\a\QCEngine\QCEngine\qcengine\programs\empirical_dispersion_resources.py", line 1052, in _get_d3_definitions
for key, params in …
```
=> access parameters on Windows

src/dftd3/param.f90
I noticed that some of the functionals defined in `get_method_id` inside `param.f90` have an alternative name in [LibXC](https://libxc.gitlab.io/functionals/).
In particular, these are:
- b1b95 = HYB_MGGA_XC_B88B95
- bhlyp = HYB_GGA_XC_BHANDHLYP (assuming that bhlyp refers to the implementation with Becke 88 exchange instead of LDA exchage - see J. Chem. Phys. 159, 114116 (2023), DOI: 10.1063/5.0167763. But please correct me if I am wrong, if it is the other way around then it would instead be HYB_GGA_XC_BHANDH)
- pbe0 = HYB_GGA_XC_PBEH
I therefore added the aliases "b88b95", "bhandhlyp", and "pbeh" for "b1b95", "bhlyp", and "pbe0", respectively, so that the D3 automatic parameter recognition based on functional name could be used with LibXC for these functionals.
=> Add LibXC alias xc names in param.f90

doc/_static/references.bib, doc/comparison.rst
I recently implemented the simple-dftd3 library into FHI-aims (https://fhi-aims.org/), as of version 240920. Therefore I updated the "Users of this library" list in the docs to reflect this.
=> Add FHI-aims to users of s-dftd3 library list

test/unit/test_dftd3.f90
Inside of dftd3, there is no check that mol%lattice is not allocated. Therefore, compiler can do some extra optimization which may lead to strange behaviour.
=> Fix Bus Error with LLVMFlang

src/dftd3/damping/atm.f90
This patch saves 30 ms per each energy evaluation for 600 atomic system just like changes between `schedule(dynamic,32) collapse(2)` and `schedule(dynamic)`. It is ~7% of total time.
=> Small optimization of atm.f90

python/dftd3/interface.py, python/dftd3/library.py, python/dftd3/meson.build, python/dftd3/pyscf.py, python/dftd3/test_interface.py, python/dftd3/test_pyscf.py, src/dftd3/gcp.f90, src/dftd3/output.f90
Closes https://github.com/dftd3/simple-dftd3/issues/122
=> Support counter-poise calculations in Python API
